name: Deploy React project to Github Pages

on:
  workflow_dispatch:
  workflow_run:
    workflows: "CI Workflow"
    types:
      - completed

jobs:
  build-deploy:
    if: ${{ github.event.workflow_run.conclusion == 'success' && github.event.workflow_run.head_branch == 'main' }}
    runs-on: ubuntu-latest

    steps:
      # Checkout repo
      - name: Checkout code
        uses: actions/checkout@v3

      # Setup NodeJS
      - name: Checkout code
        uses: actions/setup-node@v3
        with:
          node-version: 18

      # Install Dependencies
      - name: Install Dependencies
        run: npm install
      
      # Build the project
      - name: Build project
        run: npm run build
     
     # Deploy to github pages
      - name: Deploy
        uses: peaceiris/actions-gh-pages@v4
        with:
          github_token: ${{ secrets.GITHUB_TOKEN }}
          publish_dir: dist