name: test workflow

on:
  push:
    branches:
      - main
  pull_request:
    branches:
      - main
  workflow_dispatch:

jobs:
  run-tests:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
        name: checkout code

      - name: install dependencies
        run: npm install
        shell: bash

      - name: run tests
        run: npm run test
        shell: bash